"""Smoke flow integration tests.

Covers the public + authed surface every release has to keep working:

    register → POST threat → GET sensors → GET threats

Plus the four most expensive auth/validation failure modes:

  - missing Bearer header                         -> 401
  - valid key, payload's sensor_id != key's owner -> 403
  - sort_by outside the allowlist                 -> 422
  - register payload missing required field       -> 422

These are intentionally not exhaustive — they're the "did something
fundamental break since last push" gate, not the full functional test
suite.
"""

from __future__ import annotations

import pytest

from .conftest import register_sensor


pytestmark = pytest.mark.asyncio


async def test_health_returns_ok(client):
    r = await client.get("/health")
    assert r.status_code == 200
    body = r.json()
    assert body["status"] == "ok"
    assert "version" in body


async def test_register_creates_sensor(client):
    sensor_id, api_key = await register_sensor(client, "smoke-a")
    assert sensor_id.startswith("smoke-a-")
    assert len(api_key) >= 32  # generated by secrets.token_urlsafe

    # Sensor is now listed publicly
    r = await client.get("/api/v2/sensors")
    assert r.status_code == 200
    ids = [s["sensor_id"] for s in r.json()["sensors"]]
    assert sensor_id in ids


async def test_register_rejects_bad_name(client):
    """Name validation runs after normalisation; an empty string slugs to
    'sensor' (a valid name), but Pydantic's min_length=1 catches the truly
    empty input first."""
    r = await client.post(
        "/api/v2/sensors/register",
        json={"requested_name": "", "capabilities": {}, "enabled_detectors": []},
    )
    assert r.status_code == 422


async def test_post_threat_with_valid_key(client):
    sensor_id, api_key = await register_sensor(client, "smoke-b")

    r = await client.post(
        "/api/v2/threats",
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "sensor_id": sensor_id,
            "threat_type": "test_threat",
            "detector_type": "usb",
            "severity": "high",
            "timestamp": "2026-06-25T00:00:00Z",
            "matched_rules": [{"rule_id": "test_001", "name": "test"}],
        },
    )
    assert r.status_code == 201, r.text
    body = r.json()
    assert body["sensor_id"] == sensor_id
    assert body["threat_type"] == "test_threat"

    # And the public read returns it
    r = await client.get(f"/api/v2/threats?sensor_id={sensor_id}")
    assert r.status_code == 200
    body = r.json()
    assert body["total"] == 1
    assert body["items"][0]["threat_type"] == "test_threat"


async def test_post_threat_without_auth_is_401(client):
    sensor_id, _ = await register_sensor(client, "smoke-c")
    r = await client.post(
        "/api/v2/threats",
        json={
            "sensor_id": sensor_id,
            "threat_type": "x",
            "detector_type": "usb",
            "severity": "low",
            "timestamp": "2026-06-25T00:00:00Z",
        },
    )
    assert r.status_code == 401


async def test_post_threat_cross_sensor_is_403(client):
    """Sensor A's key trying to push as sensor B is the audit's F3 — has
    to stay a 403 forever, this is the single most important auth check
    in the system."""
    a_id, a_key = await register_sensor(client, "smoke-d")
    b_id, _ = await register_sensor(client, "smoke-e")

    r = await client.post(
        "/api/v2/threats",
        headers={"Authorization": f"Bearer {a_key}"},
        json={
            "sensor_id": b_id,                   # ← key belongs to A
            "threat_type": "impersonation",
            "detector_type": "usb",
            "severity": "critical",
            "timestamp": "2026-06-25T00:00:00Z",
        },
    )
    assert r.status_code == 403


async def test_threats_sort_by_allowlist(client):
    """sort_by is regex-constrained; anything outside the allowlist must
    422 (FastAPI's query validation) rather than 500."""
    r = await client.get("/api/v2/threats?sort_by=__class__")
    assert r.status_code == 422


async def test_threat_payload_caps(client):
    """Pydantic max_length on matched_rules is 32 — payloads over the cap
    are rejected before they hit the DB."""
    sensor_id, api_key = await register_sensor(client, "smoke-f")

    over_cap = [{"rule_id": f"r{i}", "name": "x"} for i in range(33)]
    r = await client.post(
        "/api/v2/threats",
        headers={"Authorization": f"Bearer {api_key}"},
        json={
            "sensor_id": sensor_id,
            "threat_type": "t",
            "detector_type": "usb",
            "severity": "low",
            "timestamp": "2026-06-25T00:00:00Z",
            "matched_rules": over_cap,
        },
    )
    assert r.status_code == 422
