filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/honeypot/*.log
  fields:
    log_source: honeypot
  fields_under_root: true

output.elasticsearch:
  hosts: ['elasticsearch:9200']

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 3
  rotateeverybytes: 10485760
